/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Lexer.TokenType;
import java.io.FileReader;
import java.io.IOException;

public class Compiler {
    public static void main(String[] args) {
        if (args.length < 2) {
            System.err.println("java main -lexer <filepath>");
            System.exit(1);
        }
        if (!args[0].equals("-lexer")) {
            System.err.println("-lexer est obligatoire");
            System.exit(1);
        }

        String filePath = args[1];

        try (FileReader reader = new FileReader(filePath)) {
            Lexer lexer = new Lexer(reader);
            Symbol symbol;
            symbol = lexer.getNextSymbol();

            while (symbol.getType() != TokenType.EOF) {
                System.out.println(symbol);
                symbol = lexer.getNextSymbol();
            }
        } catch (IOException e) {
            System.err.println("Erreur de lecture du fichier");
        }
    }
}
